import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
https://github.com/daaru00/obsidian-time-tracker/
*/
`;

export default {
    input: './src/main.ts',
    output: {
        dir: '.',
        sourcemap: 'inline',
        format: 'cjs',
        exports: 'default',
        banner,
    },
    external: ['obsidian', 'fs', 'os', 'child_process', 'path', 'crypto', 'buffer', 'process', 'stream', 'https', 'http', 'http2'],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        json()
    ]
};
